services:
  postgres:
    image: postgres:16
    container_name: hospital_postgres
    restart: always
    environment:
         POSTGRES_USER: hospital_user
         POSTGRES_PASSWORD: hospital123
         POSTGRES_DB: hospital_db
    ports:
         - "5432:5432"
    volumes:
         - postgres_data:/var/lib/postgresql/data
    networks:
      - hospital_network
         


  pgadmin:
    image: dpage/pgadmin4
    container_name: hospital_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hospital.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
     - hospital_network


volumes:
  postgres_data:
networks:
  hospital_network: